from data_stark import lista_personajes
from calculos import stark_normalizar_datos
from calculos import obtener_nombre
from calculos import imprimir_dato
from calculos import stark_imprimir_nombres_heroes

stark_imprimir_nombres_heroes(lista_personajes)